# Generated by Django 4.1.7 on 2023-03-09 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mmapp', '0003_remove_note_notebooks_notebook_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='notes',
        ),
        migrations.AddField(
            model_name='note',
            name='notebooks',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mmapp.notebook'),
            preserve_default=False,
        ),
    ]
