# Generated by Django 4.1.7 on 2023-03-20 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mmapp', '0004_remove_notebook_notes_note_notebooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='notebooks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='mmapp.notebook'),
        ),
    ]
