# Generated by Django 4.1.7 on 2023-03-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmapp', '0002_remove_notebook_notes_note_notebooks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='notebooks',
        ),
        migrations.AddField(
            model_name='notebook',
            name='notes',
            field=models.ManyToManyField(to='mmapp.note'),
        ),
    ]
