# Generated by Django 4.1 on 2023-03-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mmapp", "0005_alter_note_notebooks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="file_content",
        ),
        migrations.AddField(
            model_name="notebook",
            name="corpus",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="notebook",
            name="kv",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="notebook",
            name="kv_vectors",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="notebook",
            name="oov",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="notebook",
            name="vocab",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
