# Generated by Django 4.1 on 2023-03-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mmapp", "0006_remove_note_file_content_notebook_corpus_notebook_kv_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notebook",
            name="oov",
        ),
        migrations.AddField(
            model_name="note",
            name="corpus",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="note",
            name="vocab",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
